#ifndef _LPTARENDERERSTATUSCODES_H_
#define _LPTARENDERERSTATUSCODES_H_
#include "LptaStatusCodes.h"

#define    LPTA_RDR_FAIL (LPTA_FAIL | 0x20000000)

#define LPTA_RDR_CREATEAPI_FAIL (LPTA_RENDERER_FAIL | 0x000000001)

#endif