#ifndef _RENDERSTATES_H_
#define _RENDERSTATES_H_

namespace lpta
{

typedef enum RENDER_CULL_MODE_TYPE
{
    RS_CULL_CW,
    RS_CULL_CCW,
    RS_CULL_NONE,
} RENDER_CULL_MODE;

typedef enum RENDER_DEPTH_MODE_TYPE
{
    RS_DEPTH_READWRTE,
    RS_DEPTH_READONLY,
    RS_DEPTH_NONE,
} RENDER_DEPTH_MODE;

typedef enum RENDER_SHADE_MODE_TYPE
{
    RS_SHADE_TRIWIRE,
    RS_SHADE_HULLWIRE,
    RS_SHADE_SOLID,
} RENDER_SHADE_MODE;

typedef enum RENDER_POINT_MODE_TYPE
{
    RS_POINT_SPRITE,
    RS_POINT_NONE,
} RENDER_POINT_MODE;

}

#endif